//export default function randomWords() {
//  return true;
//}


//let nouns = ["hate", "knowledge", "spring", "power", "secret", "fang", "waves", "fall", "arm", "rose", "force", "earth", "sense", "destruction", "brother", "hook", "swing", "cellar", "stone", "cloth", "dispatch", "rain", "battle", "grouper", "burst", "mother", "whip", "powder", "committee", "angel", "demon", "church", "altar", "station", "suggestion", "road", "desert", "desire", "sleep", "time", "bird", "cage", "elephant", "spider", "motion", "selection", "farm", "connection", "needle", "wax", "dust", "prophet", "end", "tendency", "distance", "dirt", "throat", "spear", "arrow", "act", "drop", "cliff", "waterfall", "experience", "control", "noise", "train", "ball", "dog", "amount", "glove", "crayon", "base", "harbor", "sweater", "stage", "crow", "unicorn", "plunge", "tempest", "ship", "storm", "rage", "tundra", "covfefe", "weasel", "leopard", "eagle", "unicorn", "disaster", "fury", "dragon", "ninja"]; 
let nouns = [
  "altar",
  "angel",
  "arrow",
  "battle",
  "brother",
  "burst",
  "cage",
  "cellar",
  "cliff",
  "connection",
  "control",
  "covfefe",
  "demon",
  "desert",
  "desire",
  "destruction",
  "disaster",
  "dispatch",
  "distance",
  "dog",
  "dragon",
  "dust",
  "eagle",
  "earth",
  "elephant",
  "explosion",
  "fall",
  "fang",
  "farm",
  "force",
  "fury",
  "golem",
  "grouper",
  "hand",
  "harbor",
  "hate",
  "hook",
  "knowledge",
  "leopard",
  "lightning",
  "mantis",
  "matrix",
  "mother",
  "motion",
  "needle",
  "ninja",
  "noise",
  "plunge",
  "power",
  "prophet",
  "rage",
  "rain",
  "rapture",
  "raven",
  "road",
  "rose",
  "secret",
  "sense",
  "shark",
  "ship",
  "sleep",
  "spear",
  "spider",
  "spring",
  "station",
  "stone",
  "storm",
  "strike",
  "swing",
  "tempest",
  "thunder",
  "tiger",
  "time",
  "tornado",
  "totality",
  "train",
  "tundra",
  "unicorn",
  "unicorn",
  "waterfall",
  "waves",
  "weasel",
  "whip"
];

let adjectives = [
  "ancient",
  "angry",
  "blood",
  "chief",
  "colossal",
  "corpulent",
  "crucial",
  "crushed",
  "damaged",
  "dangerous",
  "dazzling",
  "deadly",
  "deafening",
  "death",
  "defeated",
  "disastrous",
  "double",
  "dusty",
  "empty",
  "epic",
  "eternal",
  "fatal",
  "fateful",
  "flawless",
  "fragile",
  "fresh",
  "giant",
  "greedy",
  "gruesome",
  "heavy",
  "icy",
  "ignorant",
  "jolly good",
  "killer",
  "moldy",
  "pathetic",
  "powerful",
  "psychotic",
  "rightful",
  "rotten",
  "scorched",
  "secret",
  "seventh",
  "sordid",
  "tiny",
  "tranquil",
  "ugly",
  "undead",
  "weathered",
  "wicked",
  "withered",
  "wretched"
];

let randomInt = function(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

const funcs = {
  randomNoun() {
    return nouns[randomInt(0, nouns.length-1)];
  }, 
  randomAdjective() {
    return adjectives[randomInt(0, adjectives.length-1)];
  }
};

export default funcs;
